ALTER TABLE game_state
    ADD COLUMN IF NOT EXISTS winmult_inf_level   INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bonusmult_inf_level INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS clickmult_inf_level INTEGER NOT NULL DEFAULT 0;
