ALTER TABLE game_state
    ADD COLUMN IF NOT EXISTS click_window_start TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS click_window_count INTEGER      NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS frenzy_last_tick   TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01';
